apiVersion: v1
kind: ServiceAccount
metadata:
  name: alex
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: andrew
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: den
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: max
  namespace: default